background            #171C14

color0                #171C14
color1                #A85A2B
color2                #8AB870
color3                #C2A04A
color4                #8AB58C
color5                #6E5034
color6                #A9D694
color7                #D6DAC5
color8                #B9BBA9
color9                #C8703A
color10               #B3D89B
color11               #E8D49B
color12               #CBE3C3
color13               #B89970
color14               #EFFFE1
color15               #D6E9C6

cursor                #D6DAC5

foreground            #D6DAC5

selection_background  #D9E7CA
selection_foreground  #434F3A

# Override obscure colors for starship prompt (these are greys at the end)
color255              #AAD290
color254              #2E4F1C
color253              #BDCBAF
color252              #434F3A
color251              #C4A37A
color250              #3A2A1F
color249              #D68A4C
color248              #5C2E15

color232              #183806
color233              #C6EFAA
color234              #283420
color235              #D9E7CA
color236              #2A1810
color237              #E8D4B8
color238              #2A1810
color239              #F5D4B0
color240              #183806 // Somehow 232 doesn't work so i gotta use another number

# Some stuff should specifically use the colors in the middle so they look acceptable in both unthemed light/dark
color243              #AAD290
color244              #D68A4C
color245              #43483E
