# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors.
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays

# FW16 internal display — 2560x1600 @ 165 Hz, fractional scale for 16" HiDPI panel.
monitor = eDP-1, 2560x1600@165, 0x0, 1.0
