# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5


# Lock immediately on session start (paired with greetd auto-login)
exec-once = sleep 0.5 && hyprlock --immediate
